// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: v1/telegram_service.proto

package telegramservicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_PASSWORD_NEEDED   SessionStatus = 0
	SessionStatus_SESSION_STATUS_AUTHORIZED        SessionStatus = 1
	SessionStatus_SESSION_STATUS_UNAUTHENTICATED   SessionStatus = 2
	SessionStatus_SESSION_STATUS_SESSION_NOT_FOUND SessionStatus = 3
	SessionStatus_SESSION_STATUS_DEADLINE_EXCEEDED SessionStatus = 4
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_PASSWORD_NEEDED",
		1: "SESSION_STATUS_AUTHORIZED",
		2: "SESSION_STATUS_UNAUTHENTICATED",
		3: "SESSION_STATUS_SESSION_NOT_FOUND",
		4: "SESSION_STATUS_DEADLINE_EXCEEDED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_PASSWORD_NEEDED":   0,
		"SESSION_STATUS_AUTHORIZED":        1,
		"SESSION_STATUS_UNAUTHENTICATED":   2,
		"SESSION_STATUS_SESSION_NOT_FOUND": 3,
		"SESSION_STATUS_DEADLINE_EXCEEDED": 4,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_telegram_service_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_v1_telegram_service_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_telegram_service_proto_rawDescGZIP(), []int{0}
}

type SessionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status        SessionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=pact.telegram.v1.SessionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionState) Reset() {
	*x = SessionState{}
	mi := &file_v1_telegram_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionState) ProtoMessage() {}

func (x *SessionState) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telegram_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionState.ProtoReflect.Descriptor instead.
func (*SessionState) Descriptor() ([]byte, []int) {
	return file_v1_telegram_service_proto_rawDescGZIP(), []int{0}
}

func (x *SessionState) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SessionState) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_PASSWORD_NEEDED
}

type CreateSessionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*CreateSessionEvent_SessionResponse
	//	*CreateSessionEvent_SessionState
	Event         isCreateSessionEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionEvent) Reset() {
	*x = CreateSessionEvent{}
	mi := &file_v1_telegram_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionEvent) ProtoMessage() {}

func (x *CreateSessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telegram_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionEvent.ProtoReflect.Descriptor instead.
func (*CreateSessionEvent) Descriptor() ([]byte, []int) {
	return file_v1_telegram_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionEvent) GetEvent() isCreateSessionEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *CreateSessionEvent) GetSessionResponse() *CreateSessionResponse {
	if x != nil {
		if x, ok := x.Event.(*CreateSessionEvent_SessionResponse); ok {
			return x.SessionResponse
		}
	}
	return nil
}

func (x *CreateSessionEvent) GetSessionState() *SessionState {
	if x != nil {
		if x, ok := x.Event.(*CreateSessionEvent_SessionState); ok {
			return x.SessionState
		}
	}
	return nil
}

type isCreateSessionEvent_Event interface {
	isCreateSessionEvent_Event()
}

type CreateSessionEvent_SessionResponse struct {
	SessionResponse *CreateSessionResponse `protobuf:"bytes,1,opt,name=session_response,json=sessionResponse,proto3,oneof"`
}

type CreateSessionEvent_SessionState struct {
	SessionState *SessionState `protobuf:"bytes,2,opt,name=session_state,json=sessionState,proto3,oneof"`
}

func (*CreateSessionEvent_SessionResponse) isCreateSessionEvent_Event() {}

func (*CreateSessionEvent_SessionState) isCreateSessionEvent_Event() {}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	QrCode        string                 `protobuf:"bytes,2,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_v1_telegram_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telegram_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_v1_telegram_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

type SubmitPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPasswordRequest) Reset() {
	*x = SubmitPasswordRequest{}
	mi := &file_v1_telegram_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPasswordRequest) ProtoMessage() {}

func (x *SubmitPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telegram_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPasswordRequest.ProtoReflect.Descriptor instead.
func (*SubmitPasswordRequest) Descriptor() ([]byte, []int) {
	return file_v1_telegram_service_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitPasswordRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubmitPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SubmitPasswordEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*SubmitPasswordEvent_Empty
	//	*SubmitPasswordEvent_SessionState
	Event         isSubmitPasswordEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPasswordEvent) Reset() {
	*x = SubmitPasswordEvent{}
	mi := &file_v1_telegram_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPasswordEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPasswordEvent) ProtoMessage() {}

func (x *SubmitPasswordEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telegram_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPasswordEvent.ProtoReflect.Descriptor instead.
func (*SubmitPasswordEvent) Descriptor() ([]byte, []int) {
	return file_v1_telegram_service_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitPasswordEvent) GetEvent() isSubmitPasswordEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SubmitPasswordEvent) GetEmpty() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Event.(*SubmitPasswordEvent_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

func (x *SubmitPasswordEvent) GetSessionState() *SessionState {
	if x != nil {
		if x, ok := x.Event.(*SubmitPasswordEvent_SessionState); ok {
			return x.SessionState
		}
	}
	return nil
}

type isSubmitPasswordEvent_Event interface {
	isSubmitPasswordEvent_Event()
}

type SubmitPasswordEvent_Empty struct {
	Empty *emptypb.Empty `protobuf:"bytes,1,opt,name=empty,proto3,oneof"`
}

type SubmitPasswordEvent_SessionState struct {
	SessionState *SessionState `protobuf:"bytes,2,opt,name=session_state,json=sessionState,proto3,oneof"`
}

func (*SubmitPasswordEvent_Empty) isSubmitPasswordEvent_Event() {}

func (*SubmitPasswordEvent_SessionState) isSubmitPasswordEvent_Event() {}

// ------- DELETE SESSION -------
type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_v1_telegram_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telegram_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_v1_telegram_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Peer          string                 `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_v1_telegram_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telegram_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_v1_telegram_service_proto_rawDescGZIP(), []int{6}
}

func (x *SendMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_v1_telegram_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telegram_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_v1_telegram_service_proto_rawDescGZIP(), []int{7}
}

func (x *SendMessageResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type SubscribeMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeMessagesRequest) Reset() {
	*x = SubscribeMessagesRequest{}
	mi := &file_v1_telegram_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeMessagesRequest) ProtoMessage() {}

func (x *SubscribeMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telegram_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeMessagesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeMessagesRequest) Descriptor() ([]byte, []int) {
	return file_v1_telegram_service_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type MessageUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageUpdate) Reset() {
	*x = MessageUpdate{}
	mi := &file_v1_telegram_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUpdate) ProtoMessage() {}

func (x *MessageUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_v1_telegram_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUpdate.ProtoReflect.Descriptor instead.
func (*MessageUpdate) Descriptor() ([]byte, []int) {
	return file_v1_telegram_service_proto_rawDescGZIP(), []int{9}
}

func (x *MessageUpdate) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageUpdate) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MessageUpdate) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_v1_telegram_service_proto protoreflect.FileDescriptor

const file_v1_telegram_service_proto_rawDesc = "" +
	"\n" +
	"\x19v1/telegram_service.proto\x12\x10pact.telegram.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"a\n" +
	"\fSessionState\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.pact.telegram.v1.SessionStatusR\x06status\"\xba\x01\n" +
	"\x12CreateSessionEvent\x12T\n" +
	"\x10session_response\x18\x01 \x01(\v2'.pact.telegram.v1.CreateSessionResponseH\x00R\x0fsessionResponse\x12E\n" +
	"\rsession_state\x18\x02 \x01(\v2\x1e.pact.telegram.v1.SessionStateH\x00R\fsessionStateB\a\n" +
	"\x05event\"O\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aqr_code\x18\x02 \x01(\tR\x06qrCode\"R\n" +
	"\x15SubmitPasswordRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x95\x01\n" +
	"\x13SubmitPasswordEvent\x12.\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x05empty\x12E\n" +
	"\rsession_state\x18\x02 \x01(\v2\x1e.pact.telegram.v1.SessionStateH\x00R\fsessionStateB\a\n" +
	"\x05event\"5\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"[\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04peer\x18\x02 \x01(\tR\x04peer\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"4\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"9\n" +
	"\x18SubscribeMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x90\x01\n" +
	"\rMessageUpdate\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*\xc2\x01\n" +
	"\rSessionStatus\x12\"\n" +
	"\x1eSESSION_STATUS_PASSWORD_NEEDED\x10\x00\x12\x1d\n" +
	"\x19SESSION_STATUS_AUTHORIZED\x10\x01\x12\"\n" +
	"\x1eSESSION_STATUS_UNAUTHENTICATED\x10\x02\x12$\n" +
	" SESSION_STATUS_SESSION_NOT_FOUND\x10\x03\x12$\n" +
	" SESSION_STATUS_DEADLINE_EXCEEDED\x10\x042\xd5\x03\n" +
	"\x0fTelegramService\x12O\n" +
	"\rCreateSession\x12\x16.google.protobuf.Empty\x1a$.pact.telegram.v1.CreateSessionEvent0\x01\x12`\n" +
	"\x0eSubmitPassword\x12'.pact.telegram.v1.SubmitPasswordRequest\x1a%.pact.telegram.v1.SubmitPasswordEvent\x12O\n" +
	"\rDeleteSession\x12&.pact.telegram.v1.DeleteSessionRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\vSendMessage\x12$.pact.telegram.v1.SendMessageRequest\x1a%.pact.telegram.v1.SendMessageResponse\x12b\n" +
	"\x11SubscribeMessages\x12*.pact.telegram.v1.SubscribeMessagesRequest\x1a\x1f.pact.telegram.v1.MessageUpdate0\x01BCZAgithub.com/ummuys/pacttelegramservice/api/pb/v1;telegramservicev1b\x06proto3"

var (
	file_v1_telegram_service_proto_rawDescOnce sync.Once
	file_v1_telegram_service_proto_rawDescData []byte
)

func file_v1_telegram_service_proto_rawDescGZIP() []byte {
	file_v1_telegram_service_proto_rawDescOnce.Do(func() {
		file_v1_telegram_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_telegram_service_proto_rawDesc), len(file_v1_telegram_service_proto_rawDesc)))
	})
	return file_v1_telegram_service_proto_rawDescData
}

var file_v1_telegram_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_telegram_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_telegram_service_proto_goTypes = []any{
	(SessionStatus)(0),               // 0: pact.telegram.v1.SessionStatus
	(*SessionState)(nil),             // 1: pact.telegram.v1.SessionState
	(*CreateSessionEvent)(nil),       // 2: pact.telegram.v1.CreateSessionEvent
	(*CreateSessionResponse)(nil),    // 3: pact.telegram.v1.CreateSessionResponse
	(*SubmitPasswordRequest)(nil),    // 4: pact.telegram.v1.SubmitPasswordRequest
	(*SubmitPasswordEvent)(nil),      // 5: pact.telegram.v1.SubmitPasswordEvent
	(*DeleteSessionRequest)(nil),     // 6: pact.telegram.v1.DeleteSessionRequest
	(*SendMessageRequest)(nil),       // 7: pact.telegram.v1.SendMessageRequest
	(*SendMessageResponse)(nil),      // 8: pact.telegram.v1.SendMessageResponse
	(*SubscribeMessagesRequest)(nil), // 9: pact.telegram.v1.SubscribeMessagesRequest
	(*MessageUpdate)(nil),            // 10: pact.telegram.v1.MessageUpdate
	(*emptypb.Empty)(nil),            // 11: google.protobuf.Empty
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
}
var file_v1_telegram_service_proto_depIdxs = []int32{
	0,  // 0: pact.telegram.v1.SessionState.status:type_name -> pact.telegram.v1.SessionStatus
	3,  // 1: pact.telegram.v1.CreateSessionEvent.session_response:type_name -> pact.telegram.v1.CreateSessionResponse
	1,  // 2: pact.telegram.v1.CreateSessionEvent.session_state:type_name -> pact.telegram.v1.SessionState
	11, // 3: pact.telegram.v1.SubmitPasswordEvent.empty:type_name -> google.protobuf.Empty
	1,  // 4: pact.telegram.v1.SubmitPasswordEvent.session_state:type_name -> pact.telegram.v1.SessionState
	12, // 5: pact.telegram.v1.MessageUpdate.timestamp:type_name -> google.protobuf.Timestamp
	11, // 6: pact.telegram.v1.TelegramService.CreateSession:input_type -> google.protobuf.Empty
	4,  // 7: pact.telegram.v1.TelegramService.SubmitPassword:input_type -> pact.telegram.v1.SubmitPasswordRequest
	6,  // 8: pact.telegram.v1.TelegramService.DeleteSession:input_type -> pact.telegram.v1.DeleteSessionRequest
	7,  // 9: pact.telegram.v1.TelegramService.SendMessage:input_type -> pact.telegram.v1.SendMessageRequest
	9,  // 10: pact.telegram.v1.TelegramService.SubscribeMessages:input_type -> pact.telegram.v1.SubscribeMessagesRequest
	2,  // 11: pact.telegram.v1.TelegramService.CreateSession:output_type -> pact.telegram.v1.CreateSessionEvent
	5,  // 12: pact.telegram.v1.TelegramService.SubmitPassword:output_type -> pact.telegram.v1.SubmitPasswordEvent
	11, // 13: pact.telegram.v1.TelegramService.DeleteSession:output_type -> google.protobuf.Empty
	8,  // 14: pact.telegram.v1.TelegramService.SendMessage:output_type -> pact.telegram.v1.SendMessageResponse
	10, // 15: pact.telegram.v1.TelegramService.SubscribeMessages:output_type -> pact.telegram.v1.MessageUpdate
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_v1_telegram_service_proto_init() }
func file_v1_telegram_service_proto_init() {
	if File_v1_telegram_service_proto != nil {
		return
	}
	file_v1_telegram_service_proto_msgTypes[1].OneofWrappers = []any{
		(*CreateSessionEvent_SessionResponse)(nil),
		(*CreateSessionEvent_SessionState)(nil),
	}
	file_v1_telegram_service_proto_msgTypes[4].OneofWrappers = []any{
		(*SubmitPasswordEvent_Empty)(nil),
		(*SubmitPasswordEvent_SessionState)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_telegram_service_proto_rawDesc), len(file_v1_telegram_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_telegram_service_proto_goTypes,
		DependencyIndexes: file_v1_telegram_service_proto_depIdxs,
		EnumInfos:         file_v1_telegram_service_proto_enumTypes,
		MessageInfos:      file_v1_telegram_service_proto_msgTypes,
	}.Build()
	File_v1_telegram_service_proto = out.File
	file_v1_telegram_service_proto_goTypes = nil
	file_v1_telegram_service_proto_depIdxs = nil
}
