// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: v1/telegram_service.proto

package telegramservicev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelegramService_CreateSession_FullMethodName     = "/pact.telegram.v1.TelegramService/CreateSession"
	TelegramService_SubmitPassword_FullMethodName    = "/pact.telegram.v1.TelegramService/SubmitPassword"
	TelegramService_DeleteSession_FullMethodName     = "/pact.telegram.v1.TelegramService/DeleteSession"
	TelegramService_SendMessage_FullMethodName       = "/pact.telegram.v1.TelegramService/SendMessage"
	TelegramService_SubscribeMessages_FullMethodName = "/pact.telegram.v1.TelegramService/SubscribeMessages"
)

// TelegramServiceClient is the client API for TelegramService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelegramServiceClient interface {
	CreateSession(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateSessionEvent], error)
	SubmitPassword(ctx context.Context, in *SubmitPasswordRequest, opts ...grpc.CallOption) (*SubmitPasswordEvent, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	SubscribeMessages(ctx context.Context, in *SubscribeMessagesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageUpdate], error)
}

type telegramServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelegramServiceClient(cc grpc.ClientConnInterface) TelegramServiceClient {
	return &telegramServiceClient{cc}
}

func (c *telegramServiceClient) CreateSession(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateSessionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelegramService_ServiceDesc.Streams[0], TelegramService_CreateSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, CreateSessionEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelegramService_CreateSessionClient = grpc.ServerStreamingClient[CreateSessionEvent]

func (c *telegramServiceClient) SubmitPassword(ctx context.Context, in *SubmitPasswordRequest, opts ...grpc.CallOption) (*SubmitPasswordEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitPasswordEvent)
	err := c.cc.Invoke(ctx, TelegramService_SubmitPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TelegramService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, TelegramService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramServiceClient) SubscribeMessages(ctx context.Context, in *SubscribeMessagesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelegramService_ServiceDesc.Streams[1], TelegramService_SubscribeMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeMessagesRequest, MessageUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelegramService_SubscribeMessagesClient = grpc.ServerStreamingClient[MessageUpdate]

// TelegramServiceServer is the server API for TelegramService service.
// All implementations must embed UnimplementedTelegramServiceServer
// for forward compatibility.
type TelegramServiceServer interface {
	CreateSession(*emptypb.Empty, grpc.ServerStreamingServer[CreateSessionEvent]) error
	SubmitPassword(context.Context, *SubmitPasswordRequest) (*SubmitPasswordEvent, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*emptypb.Empty, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	SubscribeMessages(*SubscribeMessagesRequest, grpc.ServerStreamingServer[MessageUpdate]) error
	mustEmbedUnimplementedTelegramServiceServer()
}

// UnimplementedTelegramServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelegramServiceServer struct{}

func (UnimplementedTelegramServiceServer) CreateSession(*emptypb.Empty, grpc.ServerStreamingServer[CreateSessionEvent]) error {
	return status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedTelegramServiceServer) SubmitPassword(context.Context, *SubmitPasswordRequest) (*SubmitPasswordEvent, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitPassword not implemented")
}
func (UnimplementedTelegramServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedTelegramServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedTelegramServiceServer) SubscribeMessages(*SubscribeMessagesRequest, grpc.ServerStreamingServer[MessageUpdate]) error {
	return status.Error(codes.Unimplemented, "method SubscribeMessages not implemented")
}
func (UnimplementedTelegramServiceServer) mustEmbedUnimplementedTelegramServiceServer() {}
func (UnimplementedTelegramServiceServer) testEmbeddedByValue()                         {}

// UnsafeTelegramServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelegramServiceServer will
// result in compilation errors.
type UnsafeTelegramServiceServer interface {
	mustEmbedUnimplementedTelegramServiceServer()
}

func RegisterTelegramServiceServer(s grpc.ServiceRegistrar, srv TelegramServiceServer) {
	// If the following call panics, it indicates UnimplementedTelegramServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelegramService_ServiceDesc, srv)
}

func _TelegramService_CreateSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TelegramServiceServer).CreateSession(m, &grpc.GenericServerStream[emptypb.Empty, CreateSessionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelegramService_CreateSessionServer = grpc.ServerStreamingServer[CreateSessionEvent]

func _TelegramService_SubmitPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).SubmitPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_SubmitPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).SubmitPassword(ctx, req.(*SubmitPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramService_SubscribeMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeMessagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TelegramServiceServer).SubscribeMessages(m, &grpc.GenericServerStream[SubscribeMessagesRequest, MessageUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelegramService_SubscribeMessagesServer = grpc.ServerStreamingServer[MessageUpdate]

// TelegramService_ServiceDesc is the grpc.ServiceDesc for TelegramService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelegramService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pact.telegram.v1.TelegramService",
	HandlerType: (*TelegramServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitPassword",
			Handler:    _TelegramService_SubmitPassword_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _TelegramService_DeleteSession_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _TelegramService_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateSession",
			Handler:       _TelegramService_CreateSession_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeMessages",
			Handler:       _TelegramService_SubscribeMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v1/telegram_service.proto",
}
